### ISSUE TITLE
Android auto showing blank screen now

### ISSUE THREAD

**Issue by cremonies** [advplyr/audiobookshelf-app#1081]
### Steps to reproduce

1. Connect phone to car
2. Open audiobookshelf though android auto car screen

### Expected behaviour
- connects to server and shows available books

### Actual behaviour
- shows an empty download screen

If I open the app before connecting it to the car it will connect to the server and shows the books on the car screen. 
If I open the phone app after connect it to the car, I have to unplug it or select the book though the phone to play it.

**Comment by donkevlar** [comment]
I have experienced this as well.

**Comment by cremonies** [comment]
Did your just start happening like mine? I just updated a week ago and
noticed it happening now.
I was trying to find if I needed to change a setting with reverse proxy.

**Comment by donkevlar** [comment]
My main issue seems to be that if I don't open the app prior to android auto launching, no socket connection is established. So it goes to the downloads screen.

**Comment by donkevlar** [comment]
Even after the app is open on my phone, the android auto app doesn't change, unless I restart android auto or reconnect my device to my car.

**Comment by cremonies** [comment]
> Even after the app is open on my phone, the android auto app doesn't change, unless I restart android auto or reconnect my device to my car.

I have the exact same issue.
How long have you been using the app and was this always an issue?
I'm trying to find out why this is now happening and didn't before.

**Comment by aureateflux** [comment]
It's happening to me as well. I kinda thought I had navigated to the downloads screen and there was no way back from there.

Testing it, I see that @donkevlar is correct: if the app is open when Android Auto starts, the browsing screen (as opposed to the playing screen) fully populates with tabs for "listening," "libraries," and "Downloads."

The first level into each of those tabs has no "back" functionality because you are expected to click directly to one of the other tabs (when you select a library in that tab, it adds a back button for you to press to go back to the top level).

When only the "Downloads" tab is generated because of this bug, you don't get access to the other tabs. You can still run books and podcasts from the app on the phone, but it doesn't seem to refresh this page after it fails the first time.

**Comment by advplyr** [comment]
I fixed this for the next release.

The way this will work is pressing the "disconnect" button in the side drawer will put the app in "offline mode". Once in offline mode the app doesn't try to connect to the server on subsequent app launches. 

That way if you were going off grid for a while you can stop android auto and the core app from trying to connect to the server every time it gets opened. Offline mode is still getting smoothed out.

**Comment by raphpa** [comment]
Also related to #310 

Of course I don't know how it works yet, but it would be great if it could be made always start offline and change to online mode automatically once a sever connection can be established to mitigate this problem.

**Comment by advplyr** [comment]
Yeah as far as I know we don't have enough control to do that in Android Auto

**Comment by ozhound** [comment]
This still happens, if ABS is open and has an active connection to the server then AA works as expected. otherwise I see an empty downloads screen with no on screen ability to do anything with ABS. 
https://github.com/advplyr/audiobookshelf-app/issues/1292
