### ISSUE TITLE
Cover Image in Downloaded Audiobook missing in Android Auto

### ISSUE THREAD

**Issue by Sacerdoss** [advplyr/audiobookshelf-app#141]
### Steps to reproduce

1. Download Audiobook from Server
2. Start Playing Audiobook
3. Cover of the Audiobook is black in the player. 

### Expected behaviour
- Cover is displayed

### Actual behaviour
- A black image is shown

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: Galaxy S10

Stock or customized system: Custom Lineage OS 18.1

#### iOS Issue
iOS Version: -

iPhone model: -

**Comment by B0rax** [comment]
On iOS I have the same problem with all audiobooks (not downloaded books)

**Comment by MidnightSnowleopard** [comment]
Downloading with 0.9.42-beta on Android with server v2.0.2 shows logs on server of "Api called without a token" for all calls to download cover.

Can provide more details if needed.

**Comment by advplyr** [comment]
This is fixed with [v0.9.43-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.43-beta)

**Comment by feerlessleadr** [comment]
It looks like this is fixed for the app itself, but the issue is still present in Android Auto (Please let me know if you'd like me to open a separate issue on this).

**Comment by advplyr** [comment]
Partially fixed in [v0.9.60-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.60-beta)

In my testing I got the cover for downloaded items to show in the list views but once starting playback the cover was not showing.

**Comment by gazpachoking** [comment]
Yeah, still having this issue on latest version. I see the small cover before I start playing the book, and covers show large in the background for streaming books, but playing a downloaded book just has a blank background on the player in android auto.

**Comment by Ansem93** [comment]
If you will work on it again I can help it testing if you want :)

**Comment by SenorSmartyPants** [comment]
Still an issue. Cover shows in queue, but not on large nowplaying screen.
Android 10, Android App version 0.9.74-beta, server ABS v2.10.1.
Book is a collection of MP3s, 1 per chapter. Book was downloaded to local in app storage (default storage on android 10).
Here's a couple screenshots. 
![IMG_20240609_171831756](https://github.com/advplyr/audiobookshelf-app/assets/991618/bfb08018-01da-4de1-a521-5ea315b9cd24)
![IMG_20240609_171837976](https://github.com/advplyr/audiobookshelf-app/assets/991618/da64132f-ed08-4a32-b22b-6d7daa4c3e51)

**Comment by JeffSchofield** [comment]
I have this issue as well. It has been going on for a couple of years. I had this problem initially, but then at one point it was fixed in an update. Recently the issue came back.

For anyone else getting the issue, how are you reaching your own instance? I am using Tailscale so I'm wondering if this is more of a config issue.

**Comment by gavinorland** [comment]
This is the number one issue for me at the moment. True, it doesn't really inhibit using the app, but it would be nice to have the image there on Android Auto :) .

> _For anyone else getting the issue, how are you reaching your own instance? I am using Tailscale so I'm wondering if this is more of a config issue._

I'm not sure what you mean by this, but for me the cover image _does_ show if the book is streaming, but _does not_ show if the book is locally downloaded.

**Comment by JeffSchofield** [comment]
> This is the number one issue for me at the moment. True, it doesn't really inhibit using the app, but it would be nice to have the image there on Android Auto :) .
> 
> > _For anyone else getting the issue, how are you reaching your own instance? I am using Tailscale so I'm wondering if this is more of a config issue._
> 
> I'm not sure what you mean by this, but for me the cover image _does_ show if the book is streaming, but _does not_ show if the book is locally downloaded.

Oh shoot, I misread this thread as no covers generally. I have this problem for both local and network on Android Auto.

I'm digging through the [related code](https://github.com/advplyr/audiobookshelf-app/blob/master/android/app/src/main/java/com/audiobookshelf/app/player/PlayerNotificationService.kt#L295) to help get some clarity. It looks like for local covers there is a different method of loading depending on SDK version. Can you clarify what version of Android you're using?

**Comment by feerlessleadr** [comment]
> > This is the number one issue for me at the moment. True, it doesn't really inhibit using the app, but it would be nice to have the image there on Android Auto :) .
> > > _For anyone else getting the issue, how are you reaching your own instance? I am using Tailscale so I'm wondering if this is more of a config issue._
> > 
> > 
> > I'm not sure what you mean by this, but for me the cover image _does_ show if the book is streaming, but _does not_ show if the book is locally downloaded.
> 
> Oh shoot, I misread this thread as no covers generally. I have this problem for both local and network on Android Auto.
> 
> I'm digging through the [related code](https://github.com/advplyr/audiobookshelf-app/blob/master/android/app/src/main/java/com/audiobookshelf/app/player/PlayerNotificationService.kt#L295) to help get some clarity. It looks like for local covers there is a different method of loading depending on SDK version. Can you clarify what version of Android you're using?

I also have this issue, but have had this across Android versions. I think all the way back as 10 or 11. I'm currently on 14.

**Comment by gavinorland** [comment]
> _Can you clarify what version of Android you're using?_

I'm using Android 12 but I saw the issue on later versions with another phone, too.

**Comment by SenorSmartyPants** [comment]
I've got it on Android 10

**Comment by Ansem93** [comment]
> > This is the number one issue for me at the moment. True, it doesn't really inhibit using the app, but it would be nice to have the image there on Android Auto :) .
> > > _For anyone else getting the issue, how are you reaching your own instance? I am using Tailscale so I'm wondering if this is more of a config issue._
> > 
> > 
> > I'm not sure what you mean by this, but for me the cover image _does_ show if the book is streaming, but _does not_ show if the book is locally downloaded.
> 
> Oh shoot, I misread this thread as no covers generally. I have this problem for both local and network on Android Auto.
> 
> I'm digging through the [related code](https://github.com/advplyr/audiobookshelf-app/blob/master/android/app/src/main/java/com/audiobookshelf/app/player/PlayerNotificationService.kt#L295) to help get some clarity. It looks like for local covers there is a different method of loading depending on SDK version. Can you clarify what version of Android you're using?

I'm on the latest 14

**Comment by Sp4rky001** [comment]
> 
> Oh shoot, I misread this thread as no covers generally. I have this problem for both local and network on Android Auto.
> 
> I'm digging through the [related code](https://github.com/advplyr/audiobookshelf-app/blob/master/android/app/src/main/java/com/audiobookshelf/app/player/PlayerNotificationService.kt#L295) to help get some clarity. It looks like for local covers there is a different method of loading depending on SDK version. Can you clarify what version of Android you're using?

Hi, thanks for pointing me in the right direction with the relevant code.  I'm a web/java programmer and never worked with Android before so it would have taken me a long time to figure out even where to look.

I think that the fix for this issue is pretty simple:  If you setIconUri, setIconBitmap will be ignored.

I modified the code like so:
```
       val mediaDescriptionBuilder = MediaDescriptionCompat.Builder()
          .setExtras(extra)
          .setTitle(currentPlaybackSession!!.displayTitle)
//          .setIconUri(coverUri)

        bitmap?.let {
          mediaDescriptionBuilder.setIconBitmap(it)
        } ?: mediaDescriptionBuilder.setIconUri(coverUri)

        return mediaDescriptionBuilder.build()
```

I compiled and tested on my on device and the artwork is showing up for both local and streamed books.

Please let me know what you think.  Thank you!
