### ISSUE TITLE
Android Auto Cannot Start Book without Stream Open in App

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf-app#167]
### Steps to reproduce

1. Ensure android app is completely closed on phone (force close if necessary)
2. Connect phone to AA and open AB 
3. Attempt to play an audiobook
4. AA is stuck at 'Getting your selection'
5. Open AB app on phone and open the same stream you are attempting to play in AA interface, the AA interface will immediately load the book stream and play

### Expected behaviour
- Should be able to start/resume a book stream directly from AA without needing to open the phone app and start the stream there first. 

### Actual behaviour
- AA will not start a new stream or resume a stream without first having the stream open on the phone app first.

### Environment data

Audiobookshelf Version:

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.43-beta

Device model: OnePlus 8T

Stock or customized system: Stock

**Comment by advplyr** [comment]
Are these audiobooks downloaded or audiobooks you are playing from your server?
If you have downloaded audiobooks I am curious if you are able to play those from AA without first opening the app.

**Comment by feerlessleadr** [comment]
Sorry for the delay getting back to you. These are streaming from my server. I don't use the downloaded audiobooks because of the bug reported [here ](https://github.com/advplyr/audiobookshelf-app/issues/112)and [here](https://github.com/advplyr/audiobookshelf-app/issues/154). I just tried downloading a book and playing it using the same steps above, and it is able to be played without issue.

**Comment by advplyr** [comment]
Next time you are going to use AA can you try first opening the app making sure you connect to your server, then close the app and open AA.

When you connect to your server it stores the last server connection config and that config is what AA attempts to connect to. If you logout of the server or if the server fails to connect it will reset that last server config variable.

This needs to be improved still, but I'm curious if this is the issue you are encountering.

**Comment by feerlessleadr** [comment]
Sure - do you want me to just open the app, or open the app and start a stream?

The reason I ask is that using AA I can browse my server library with no issue. The issue is just that once I try to start a book, it won't load.

**Comment by advplyr** [comment]
Oh good point. If you can browse the library then you must have already connected successfully to the last server config.

I don't have any suggestions now then, I'll test it out tomorrow to see if I can replicate.

**Comment by feerlessleadr** [comment]
No problem - happy to help continue to debug with server logs, etc. Thanks!

**Comment by feerlessleadr** [comment]
Just wanted to confirm that this issue still persists in 0.9.49-beta and server version 2.0.20.

**Comment by advplyr** [comment]
I'm not able to reproduce this anymore after the latest updates.

**Comment by feerlessleadr** [comment]
Thanks, I'll try that today.

I'm on Android 11 on a OnePlus 8T

**Comment by feerlessleadr** [comment]
So I'm getting some inconsistent results. I logged out of my app, forced closed it, then connected to AA. AA ABS opened no issue and I'm able to browse my server. I try playing any book (I have a combination of both local and streaming on the listening tab) and I get the "getting your selection", but nothing plays. However, if I play the same books from either the libraries or downloads tab, they play, just at the 1x playback speed, instead of 1.7x the app is set to

**Comment by advplyr** [comment]
The AA getting stuck on launch should be fixed in the latest release. There is another bug report open for the playback speed. Let me know if this persists though.

**Comment by feerlessleadr** [comment]
Do you mean latest release of the app or latest server release?

**Comment by advplyr** [comment]
Should be using the latest release of both.

**Comment by feerlessleadr** [comment]
So I'm using 2.0.22 of the server and 0.9.49-beta of the app, and the issue still is present when trying to start a book using Android auto.

**Comment by advplyr** [comment]
The media in the listening tab aren't handled any differently then the other tabs, so I wonder if this is specific to certain items or are you able to reproduce this consistently with all library items?
Are you playing downloaded items or streaming them from your server?

**Comment by advplyr** [comment]
It would be helpful to try other books, maybe if you have an mp3 one also. Or a new book you recently added to your server that isn't downloaded.

**Comment by feerlessleadr** [comment]
Ok - so I tried today to play a new book that was mp3, and when I was in AA and looking for the book in the Library tab, even though it is present on my app and my server, it was not present in the library page of AA. Upon further inspection, probably half of my library was missing from the library page on AA. 

Long story short, I'm not sure if this is related or not (and if it isn't, I can open up a separate issue on this), but because of this, I wasn't able to test since this was a new book (and I couldn't get my phone out to start the new book while driving. I'll give it a try tomorrow though, since I now have the mp3 book in the Listening section of the app.

**Comment by advplyr** [comment]
AA doesn't allow pagination so we only show a certain number of items. I'm not sure how to get around that yet. If you have the book in continue listening you will be able to play it.

**Comment by feerlessleadr** [comment]
Got it - thanks. I just tried it again with an mp3 book streaming, and the same thing happened when trying to play from the listening tab.

**Comment by advplyr** [comment]
I pushed another release fixing a crash I noticed with the db not being initialized. It's live on the play store 
[0.9.51-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.51-beta)
Please give it another try

**Comment by feerlessleadr** [comment]
Sorry to report that there is no change when trying to play from the listening tab.

**Comment by feerlessleadr** [comment]
I can confirm that I am on 2.0.23 docker on the server, and 0.9.51-beta on the app. 

I have been able to download books without issue, but hadn't tried on the latest app/server version. I forced closed the app, then downloaded a book to my phone without issue. 

In terms of scanning my library, I actually do that every day or so, since that's the only way I can add books (see [this issue](https://github.com/advplyr/audiobookshelf/issues/279) from way back when). 

Like I said though, the app itself on my phone works fine with no issues, I can both stream and play local files, download books, manage the downloaded books, etc. Even AA works great, with the exception of the above (and again, that's only an issue on the listening tab, the other 2 tabs will play the books, but only at 1x speed).

**Comment by feerlessleadr** [comment]
Just to add to this, even when I start playing a book on the app so that I can play/listen on AA, I'm still not able to select any other books (local or streaming) in AA. It always just goes back to the same book that I have open in the app.

**Comment by advplyr** [comment]
I was able to reproduce this issue and fixed it in [v0.9.52-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.52-beta)

I'm pretty confident this time but let me know!

**Comment by feerlessleadr** [comment]
I'm extremely happy to report that this is fixed. Thank you for hunting this down!
