### ISSUE TITLE
Opening a book gives an empty page

### ISSUE THREAD

**Issue by plague-doctor** [advplyr/audiobookshelf-app#809]
After upgrade server to version 2.3.x (currently running 2.3.3, but I am not sure when it started) many audiobooks give an empty page. 

Tried so far:
- re-installation of ABS app
- re-scanning of books on ABS server (including wiping current config)

No errors on the server in DEBUG logging mode.

#### Android Issue
Android version: 0.9.65-beta
Device model: OnePlus 9-PRO
Stock or customized system: LineageOS

Books are displayed correctly:
![image](https://github.com/advplyr/audiobookshelf-app/assets/10541916/3280e39d-045a-48ea-8a4e-502398c38233)

After taping on them (not all of them unfortunately):
![image](https://github.com/advplyr/audiobookshelf-app/assets/10541916/ed9af584-e499-4dab-90c6-a37fe1f8bb7f)

**Comment by advplyr** [comment]
Are the books that are giving an empty page downloaded books? Is there a pattern you can identify with the ones that show and the ones that don't?

**Comment by plague-doctor** [comment]
No, the empty page give books I try to play from the server (2.3.3 Docker).
This is a problem - I cannot figure out any pattern...

I am happy to provide one or two problematic audiobooks if it makes it easier to trouble shoot.

**Comment by advplyr** [comment]
There were 2 issues fixed related to this.

1. If you are using OPF files on your directories they may have created empty genres/tags. https://github.com/advplyr/audiobookshelf/issues/2142
2. If you are using ebooks there was a bug where the ebookFormat wasn't getting set correctly. https://github.com/advplyr/audiobookshelf/issues/2126

Both of these caused the mobile app to not load the book page. They are fixed in v2.4.4 but if you are using OPF you still have to remove those empty genres/tags.

**Comment by plague-doctor** [comment]
Nope. Still the same. There are some books in my library which play fine via the web gui, but they are not working at all with the app.
There is a zip with two such books (only short fragments of the audiobooks). I hope someone can take a look and help me to figure out what is going on there... [audiobooks.zip](https://mega.nz/file/cdshQBbI#cFeBLb7aDbsVrUQIiy24cbucBRhLK2xfbsy3Xwlgoh4)

**Comment by advplyr** [comment]
Are you using OPF files?
Do you have any ebook files with those books? Like a pdf
Are you still using an older server version v2.3.3?

**Comment by plague-doctor** [comment]
OPF - yes
no ebook files.
I am always on the latest ;-) docker 2.4.4

**Comment by advplyr** [comment]
Can you share a screenshot of the details tab for one of the books that is not loading in the mobile app?
Screenshot like this one:
![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/bbef8325-ba63-447c-aa2d-5d0f17e74202)

**Comment by plague-doctor** [comment]
![image](https://github.com/advplyr/audiobookshelf-app/assets/10541916/cc3dddb4-c675-4091-a311-9814c529a5db)

**Comment by advplyr** [comment]
Yeah you came across [#2142](https://github.com/advplyr/audiobookshelf/issues/2142)

That empty genre and tag have to be removed. This will most likely be a manual process for you unless you are comfortable opening the sqlite db.

**Comment by plague-doctor** [comment]
ouch... 
Thanks. I will need to re-visit the SQL ;-)
